version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
  spring:
    depends_on:
      - mysqldb
    image: alaamoalla/springboot-achat:latest
    container_name: achatproject
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
      
      
  